---
- hosts: "yourserver"
  tasks:
    - name: install nginx
      become: yes
      apt: name=nginx state=latest update_cache=yes
    - name: start nginx service
      service:
        name: nginx
        state: started
      become: yes
